### ISSUE TITLE
Error log when compiling DeepMagic

### ISSUE THREAD

**Issue by techwulf** [Master-Foo/DeepMagic#2]
[techwulf DeepMagic]$ dub run
Performing "debug" build using dmd for x86_64.
deepmagic 0.1.0+commit.1.g98e521f: building configuration "library"...
source/deepmagic/dom/elements/form.d-mixin-7(9,17): Error: semicolon expected, not '-'
source/deepmagic/dom/elements/form.d-mixin-7(9,17): Error: declaration expected, not '-'
source/deepmagic/dom/elements/form.d-mixin-7(10,16): Error: semicolon expected, not '-'
source/deepmagic/dom/elements/form.d-mixin-7(10,16): Error: declaration expected, not '-'
source/deepmagic/dom/elements/form.d-mixin-7(13,22): Error: semicolon expected, not '-'
source/deepmagic/dom/elements/form.d-mixin-7(13,22): Error: declaration expected, not '-'
source/deepmagic/dom/elements/form.d-mixin-7(15,4): Error: declaration expected, not 'return'
source/deepmagic/dom/elements/form.d(7,8): Error: incomplete mixin declaration ("\x0a\x09@property{\x0a\x09\x09string _accept-charset = \"\";\x0a\x09\x09string accept-charset(){\x0a\x09\x09\x09return this.tag.attr[\"accept-charset\"];\x0a\x09\x09}\x0a\x09\x09typeof(this) accept-charset(string value){\x0a\x09\x09\x09this.tag.attr[\"accept-charset\"] = value;\x0a\x09\x09\x09return this;\x0a\x09\x09}\x0a\x09}\x0a\x09")
source/deepmagic/dom/elements/form.d-mixin-20(23,10): Error: no identifier for declarator string
source/deepmagic/dom/elements/form.d-mixin-20(23,10): Error: declaration expected, not 'for'
source/deepmagic/dom/elements/form.d-mixin-20(26,16): Error: no identifier for declarator typeof(this)
source/deepmagic/dom/elements/form.d-mixin-20(26,16): Error: declaration expected, not 'for'
source/deepmagic/dom/elements/form.d-mixin-20(28,4): Error: declaration expected, not 'return'
source/deepmagic/dom/elements/form.d(20,8): Error: incomplete mixin declaration ("\x0a\x09@property{\x0a\x09\x09string _for = \"\";\x0a\x09\x09string for(){\x0a\x09\x09\x09return this.tag.attr[\"for\"];\x0a\x09\x09}\x0a\x09\x09typeof(this) for(string value){\x0a\x09\x09\x09this.tag.attr[\"for\"] = value;\x0a\x09\x09\x09return this;\x0a\x09\x09}\x0a\x09}\x0a\x09")
source/deepmagic/dom/elements/form.d-mixin-137(140,10): Error: no identifier for declarator string
source/deepmagic/dom/elements/form.d-mixin-137(140,10): Error: declaration expected, not 'for'
source/deepmagic/dom/elements/form.d-mixin-137(143,16): Error: no identifier for declarator typeof(this)
source/deepmagic/dom/elements/form.d-mixin-137(143,16): Error: declaration expected, not 'for'
source/deepmagic/dom/elements/form.d-mixin-137(145,4): Error: declaration expected, not 'return'
source/deepmagic/dom/elements/form.d(137,8): Error: incomplete mixin declaration ("\x0a\x09@property{\x0a\x09\x09string _for = \"\";\x0a\x09\x09string for(){\x0a\x09\x09\x09return this.tag.attr[\"for\"];\x0a\x09\x09}\x0a\x09\x09typeof(this) for(string value){\x0a\x09\x09\x09this.tag.attr[\"for\"] = value;\x0a\x09\x09\x09return this;\x0a\x09\x09}\x0a\x09}\x0a\x09")
dmd failed with exit code 1.

**Comment by Master-Foo** [comment]
look at source/deepmagic/dom/elements/form.d

````d
class FormElement : Html5Element!("form"){
	mixin(ElementConstructorTemplate!());
	mixin(AttributeTemplate!(typeof(this), "accept-charset"));
	mixin(AttributeTemplate!(typeof(this), "action"));
	mixin(AttributeTemplate!(typeof(this), "autocomplete"));
	mixin(AttributeTemplate!(typeof(this), "enctype"));
	mixin(AttributeTemplate!(typeof(this), "method"));
	mixin(AttributeTemplate!(typeof(this), "name"));
	mixin(AttributeTemplate!(typeof(this), "novalidate"));
	mixin(AttributeTemplate!(typeof(this), "target"));
}
````

mixin(AttributeTemplate!(typeof(this), "accept-charset")); "-" is illegal. Basically the compiler thinks you are trying to subract charset from accept

For now comment that line out. and put a TODO:

````D
//TODO: Fix accept-charset
//mixin(AttributeTemplate!(typeof(this), "accept-charset"));
````

I don't have a solution right now. Let me think about it. In the mean time, commenting out that one line should sweep the problem under the rug for now.

Then try compiling again. If there are any other similar problems after that make a similar half assed fix and document it here. Wash Rinse Repeat until it compiles.

I'm going to call it a night. I'll pick up here again in the morning when you have more info. You should be close to making it work.
